// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcnivvoesdbedrvbxauc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjbml2dm9lc2RiZWRydmJ4YXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzIzMDQsImV4cCI6MjA2OTkwODMwNH0.LN6TCprWTBdgLlSe-XYoCIv2FQfsG7KFMuALXpLaKLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});